# This is a basic workflow to help you get started with Actions

name: CI
env:
  name: shawn
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "welcome $name!"
          echo "repository1: ${{ github.repository }}"
          echo "repository2: $GITHUB_REPOSITORY"
          echo "repository3: ${repo}"
          echo "SERVER PORT: ${PORT}"
          echo "SERVER IP: $IP"
        env:
          repo: ${{ github.repository }}
          port: ${{ secrets.PORT }}
          IP: ${{ secrets.IP }}
